# Generated by Django 4.1.7 on 2024-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learningPace',
            field=models.CharField(blank=True, choices=[('Fast', 'Fast'), ('Slow', 'Slow'), ("I don't know", "I don't know")], max_length=200, null=True),
        ),
    ]
