# Generated by Django 4.1.7 on 2024-04-24 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('isCourse_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('answerType', models.CharField(blank=True, choices=[('options', 'options'), ('input', 'input')], max_length=1000, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, choices=[('lesson', 'lesson'), ('quiz', 'quiz')], max_length=1000, null=True)),
                ('timeout', models.IntegerField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lesson Detail',
            },
        ),
        migrations.CreateModel(
            name='SubjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isLesson_completed', models.BooleanField(default=False)),
                ('exercise', models.CharField(blank=True, max_length=500, null=True)),
                ('learning_type', models.CharField(blank=True, choices=[('text', 'text'), ('auditory', 'auditory'), ('interactive', 'interactive')], max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=500)),
                ('lesson_slug', models.CharField(max_length=500)),
                ('lesson_id', models.CharField(max_length=500)),
                ('lesson_details', models.ManyToManyField(blank=True, null=True, related_name='lesson_details', to='api.lessondetails')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_curriculum', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500)),
                ('exercise', models.CharField(blank=True, max_length=500, null=True)),
                ('learning_type', models.CharField(max_length=500)),
                ('isSection_completed', models.BooleanField(default=False)),
                ('course_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_course', to='api.course')),
                ('lessons', models.ManyToManyField(related_name='curriculum_lessons', to='api.subjectlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
