# Generated by Django 4.1.7 on 2024-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonobject',
            name='lesson_id',
            field=models.CharField(max_length=500),
        ),
    ]
