# Generated by Django 4.1.7 on 2024-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quicklearn_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklearn',
            name='lessonDetails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
